package POJOs;
// Generated 17-abr-2018 13:15:53 by Hibernate Tools 4.3.1



/**
 * Army generated by hbm2java
 */
public class Army  implements java.io.Serializable {


     private Integer armyId;
     private Player player;
     private String name;
     private String faction;
     private String strategy;

    public Army() {
    }

    public Army(Player player, String name, String faction, String strategy) {
       this.player = player;
       this.name = name;
       this.faction = faction;
       this.strategy = strategy;
    }
   
    public Integer getArmyId() {
        return this.armyId;
    }
    
    public void setArmyId(Integer armyId) {
        this.armyId = armyId;
    }
    public Player getPlayer() {
        return this.player;
    }
    
    public void setPlayer(Player player) {
        this.player = player;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getFaction() {
        return this.faction;
    }
    
    public void setFaction(String faction) {
        this.faction = faction;
    }
    public String getStrategy() {
        return this.strategy;
    }
    
    public void setStrategy(String strategy) {
        this.strategy = strategy;
    }




}


