package POJOs;
// Generated 17-abr-2018 18:07:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Army generated by hbm2java
 */
public class Army  implements java.io.Serializable {


     private Integer armyId;
     private Player player;
     private String name;
     private String faction;
     private String strategy;
     private Set gamesForWinnerId = new HashSet(0);
     private Set gamesForLoserId = new HashSet(0);

    public Army() {
    }

	
    public Army(Player player, String name, String faction, String strategy) {
        this.player = player;
        this.name = name;
        this.faction = faction;
        this.strategy = strategy;
    }
    public Army(Player player, String name, String faction, String strategy, Set gamesForWinnerId, Set gamesForLoserId) {
       this.player = player;
       this.name = name;
       this.faction = faction;
       this.strategy = strategy;
       this.gamesForWinnerId = gamesForWinnerId;
       this.gamesForLoserId = gamesForLoserId;
    }
   
    public Integer getArmyId() {
        return this.armyId;
    }
    
    public void setArmyId(Integer armyId) {
        this.armyId = armyId;
    }
    public Player getPlayer() {
        return this.player;
    }
    
    public void setPlayer(Player player) {
        this.player = player;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getFaction() {
        return this.faction;
    }
    
    public void setFaction(String faction) {
        this.faction = faction;
    }
    public String getStrategy() {
        return this.strategy;
    }
    
    public void setStrategy(String strategy) {
        this.strategy = strategy;
    }
    public Set getGamesForWinnerId() {
        return this.gamesForWinnerId;
    }
    
    public void setGamesForWinnerId(Set gamesForWinnerId) {
        this.gamesForWinnerId = gamesForWinnerId;
    }
    public Set getGamesForLoserId() {
        return this.gamesForLoserId;
    }
    
    public void setGamesForLoserId(Set gamesForLoserId) {
        this.gamesForLoserId = gamesForLoserId;
    }

    @Override
    public String toString() {
        return armyId + ", " + name;
    }




}


