package POJOs;
// Generated 17-abr-2018 18:07:39 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Game generated by hbm2java
 */
public class Game  implements java.io.Serializable {


     private Integer gameId;
     private Army armyByWinnerId;
     private Army armyByLoserId;
     private Date date;

    public Game() {
    }

    public Game(Army armyByWinnerId, Army armyByLoserId, Date date) {
       this.armyByWinnerId = armyByWinnerId;
       this.armyByLoserId = armyByLoserId;
       this.date = date;
    }
   
    public Integer getGameId() {
        return this.gameId;
    }
    
    public void setGameId(Integer gameId) {
        this.gameId = gameId;
    }
    public Army getArmyByWinnerId() {
        return this.armyByWinnerId;
    }
    
    public void setArmyByWinnerId(Army armyByWinnerId) {
        this.armyByWinnerId = armyByWinnerId;
    }
    public Army getArmyByLoserId() {
        return this.armyByLoserId;
    }
    
    public void setArmyByLoserId(Army armyByLoserId) {
        this.armyByLoserId = armyByLoserId;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


